language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
    - python setup.py install
    - pip install nose flake8 pep8-naming
script:
    - flake8 --ignore=E501 mintapi # pep8 flake ignoring long lines
